swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
   /user/login:
      post:
         tags:
            - User Module
         summary: Login
         description: API for Login
         parameters:
            - in: body
              name: body
              description: Login Payload
              required: true
              schema:
                 $ref: '#/definitions/Login'
         produces:
            - application/json
         responses:
            '200':
               description: Login Successfully
               schema:
                  $ref: '#/definitions/LoginResponse'
            '400':
               description: Invalid Fields
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error
   /user/signup:
      post:
         tags:
            - User Module
         summary: Signup
         description: API for Signup
         parameters:
            - in: body
              name: body
              description: Signup Payload
              required: true
              schema:
                 $ref: '#/definitions/User'
         produces:
            - application/json
         responses:
            '200':
               description: Signup Successfully
               schema:
                  $ref: '#/definitions/ApiResponse'
            '400':
               description: Invalid Fields
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error
   /user/profile:
      post:
         security:
            - Bearer: []
         tags:
            - User Module
         summary: User Profile API
         description: API for fetching a user profile
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: User profile retrieved successully
               schema:
                  $ref: '#/definitions/ApiResponse'
            '400':
               description: Invalid Fields
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error
      put:
         security:
            - Bearer: []
         tags:
            - User Module
         summary: User Profile API
         description: API for updating a user profile
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: body
              name: body
              description: Update user profile attributes
              required: true
              schema:
                 $ref: '#/definitions/UserProfile'
         produces:
            - application/json
         responses:
            '200':
               description: User profile retrieved successully
               schema:
                  $ref: '#/definitions/ApiResponse'
            '400':
               description: Invalid Fields
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error
   /user/accounts:
      get:
         security:
            - Bearer: []
         tags:
            - Accounts Module
         summary: User accounts
         description: API for fetching all the accounts of a user
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: User accounts retrieved successfully
               schema:
                  $ref: '#/definitions/AccountsResponse'
            '400':
               description: Accounts Not Found
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error

   # TRANSACTIONS
   /user/{accountID}/transactions/currentmouth:
      get:
         security:
            - Bearer: []
         tags:
            - Transactions Module
         summary: User transactions
         description: API for fetching the transactions of an account for a current month
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: path
              name: accountID
              type: string
              description: Id of the account
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: User transactions retrieved successfully
               schema:
                  $ref: '#/definitions/TransactionsResponse'
            '400':
               description: Transactions Not Found
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error

   /user/{accountID}/transactions/{transactionID}:
      get:
         security:
            - Bearer: []
         tags:
            - Transactions Module
         summary: Transaction
         description: API for fetching a transaction
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: path
              name: accountID
              type: string
              description: Id of the account
              required: true
            - in: path
              name: transactionID
              type: string
              description: Id of the transaction
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: User transaction retrieved successfully
               schema:
                  $ref: '#/definitions/TransactionResponse'
            '400':
               description: Transaction Not Found
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error

   /user/{accountID}/transactions/{transactionID}/edit:
      post:
         security:
            - Bearer: []
         tags:
            - Transactions Module
         summary: Add Infos
         description: API for adding infos on a specific transaction
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: path
              name: accountID
              type: string
              description: Id of the account
              required: true
            - in: path
              name: transactionID
              type: string
              description: Id of the transaction
              required: true
            - in: body
              name: body
              description: details to create
              schema:
                 $ref: '#/definitions/TransactionDetails'
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: Additional transaction information created successfully
               schema:
                  $ref: '#/definitions/TransactionDetailsResponse'
            '400':
               description: Invalid Fields
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error

      put:
         security:
            - Bearer: []
         tags:
            - Transactions Module
         summary: Update transaction details
         description: API for modifying the details of an existing transaction
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: path
              name: accountID
              type: string
              description: Id of the account
              required: true
            - in: path
              name: transactionID
              type: string
              description: Id of the transaction
              required: true
            - in: body
              name: body
              description: details to modify
              schema:
                 $ref: '#/definitions/TransactionDetails'
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: Transaction information updated successfully
               schema:
                  $ref: '#/definitions/TransactionDetailsResponse'
            '400':
               description: Invalid Fields
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error

   /user/{accountID}/transactions/{transactionID}/remove:
      delete:
         security:
            - Bearer: []
         tags:
            - Transactions Module
         summary: Delete transaction details
         description: API for deleting a transaction
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: path
              name: accountID
              type: string
              description: Id of the account
              required: true
            - in: path
              name: transactionID
              type: string
              description: Id of the transaction
              required: true
         produces:
            - application/json
         responses:
            '200':
               description: Transaction information deleted successfully
            '400':
               description: Invalid Fields
            '401':
               description: Invalid Token
            '404':
               description: Page not Found
            '500':
               description: Internal Server Error

securityDefinitions:
   Bearer:
      type: apiKey
      name: Authorization
      in: header

definitions:
   User:
      properties:
         email:
            type: string
            description: user email
         password:
            type: string
            description: user password
         firstName:
            type: string
            description: user first name
         lastName:
            type: string
            description: user last name
   Login:
      properties:
         email:
            type: string
            description: user email
         password:
            type: string
            description: user password
   ApiResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               id:
                  type: string
               email:
                  type: string
   LoginResponse:
      type: object
      properties:
         token:
            type: string
   UserProfile:
      type: object
      properties:
         firstName:
            type: string
         lastName:
            type: string

   AccountsResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: array
            items:
               $ref: '#/definitions/Account'

   TransactionsResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: array
            items:
               $ref: '#/definitions/Transaction'

   TransactionResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            $ref: '#/definitions/Transaction'

   TransactionDetailsResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            $ref: '#/definitions/TransactionDetails'

   Account:
      type: object
      properties:
         id:
            type: string
         label:
            type: string
         labelAccountId:
            type: string
         amount:
            type: number
         description:
            type: string

   Transaction:
      type: object
      properties:
         id:
            type: string
         accountID:
            type: string
         date:
            type: string
         description:
            type: string
         amount:
            type: number
         balance:
            type: number
         details:
            $ref: '#/definitions/TransactionDetails'

   TransactionDetails:
      type: object
      properties:
         type:
            type: string
         category:
            type: string
         notes:
            type: string
